apiVersion: v1
kind: Pod
metadata:
  name: rbd-demo-pod
  namespace: <your-namespace>
spec:
  containers:
  - name: demo-container
    image: busybox
    command: [ "sleep", "1000000" ]
    volumeMounts:
    - name: rbd-storage
      mountPath: /mnt/block-storage
  volumes:
  - name: rbd-storage
    persistentVolumeClaim:
      claimName: cephrbd-block-pvc
