---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-local-storage
  namespace: change_me
spec:
  channel: "4.7"
  installPlanApproval: Automatic
  name: openshift-local-storage
  source: redhat-operators
  sourceNamespace: openshift-marketplace
